# -*- coding: utf-8 -*-
"""18-37918-2-week-2-v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RglD-w-M1N47gDtCLLd-S8DXyf8S787c

# Name: Md. Jamil Istiaq, Id:18-37918-2, Section: F, Course: AI
week 2 v2

# Lesson 3 
# List
"""

list1=[]
list2=[0,1,2,3]
list3=['abc',['j','a','m','i','l']]
i=0
j=0
list2[i]

list3[i][j]

list2[i:j]

len(list2)

list1+list2

list2*3

for x in list2:
    3 in list2
print(list2)

list2.append(4)
list2.extend([8,9,10])
list2.sort( )
list2.index(1)
list2.insert(44, 55)
list2.reverse( )
print(list2)

del list2[i]
del list2[i:j]
list2.pop( )
#list2.remove('0')
list2[i:j] = []
print(list2)

list2[i] = 1
list2[i:j] = [4,5,6]

range(4)
x in range(0, 4)

list4 = [x**2 for x in range(5)]
print(list4)

len([1, 2, 3])

[1, 2, 3] + [4, 5, 6]

['No!'] * 4

3 in [1, 2, 3]

for x in [1, 2, 3]: print(x)

str([1, 2]) + "34"

L=['aiub','Aiub','AIUB']
L[2]

L[-2]

L[1:]

"""Reverse print of the list"""

L[::-1]

mat=[[1,2,3],[3,2,1],[4,5,6]]
mat[1]

mat[1][1]

mat[2][1]

L

L[0:2]=['university','CSE']
L

L.append('IEEE')
L

L.sort()
L

L.reverse()
L

L.pop()
L

"""# Dictionary"""

d1={}
d2={'uni':1,'aiub':2}
d3={'food':{'ham':1, 'egg':3}}

d2['aiub']
d3['food']['ham']

'uni' in d2
d2.keys( )
d2.values( )
d2.copy( )
key=0
default=0
d2.get(key, default)
d2.update(d1)

len(d1)
d2[key] = 42
del d2[key]

d2['ham'] = ['grill', 'bake', 'fry']
d2

del d2['aiub']
d2

d2['brunch'] = 'Bacon'
d2

d2 = {'spam': 2, 'ham': 1, 'eggs': 3}
d2.values( )

d2.items()

d2.get('spam')

d3 = {'toast':4, 'muffin':5}
d2.update(d3)
d2

d2.pop('muffin')
d2.pop('toast')
d2

table = {'Python': 'Guido van Rossum','Perl': 'Larry Wall','Tcl': 'John Ousterhout' }

language = 'Python'

creator = table[language]
creator

for lang in table.keys( ):
    print(lang, '\t', table[lang])

L = []
L[99] = 'spam'

D = {}
D[99] = 'spam'
D[99]
D

Matrix = {}
Matrix[(2, 3, 4)] = 88
Matrix[(7, 8, 9)] = 99
X = 2; Y = 3; Z = 4 # ; separates statements
Matrix[(X, Y, Z)]

Matrix

if Matrix[(2,3,6)]:
    print(Matrix[(2,3,6)])
else:
    print(0)
try:
    print(Matrix[(2,3,6)])
except keyError:
    print(0)

Matrix.get((2,3,4),0)

rec = {}
rec['name'] = 'mel'
rec['age'] = 45
rec['job'] = 'trainer/writer'
print(rec['name'])

mel = {'name': 'Mark','jobs': ['trainer', 'writer'],'web': 'www.rmi.net/~lutz','home': {'state': 'CO', 'zip':80513}}

mel['name']

mel['home']['zip']

{'name': 'mel', 'age': 45} # Traditional literal expression
D = {} # Assign by keys dynamically
D['name'] = 'mel'
D['age'] = 45
dict(name='mel', age=45) # Keyword argument form
dict([('name', 'mel'), ('age', 45)])

"""# Lesson 5

compare two value
"""

x=2
y=5
if x>y:
    print(x,'Grater than Y')
else: 
    print(y, 'Grater than X')

a=4 
b=5 
print(a+b)

A=1
B=2
C=3

if (A == 1 and B == 2 and C == 3):
    print('spam '*3)

while True:
    reply = input('Enter text:')
    if reply =='Exit': break
    print(reply.upper( ))

"""simple square calculation, break for single calculation, if there "break" not then it wants value one after one calculation """

while True:
    x = int(input('Enter Number:'))
    x=x**2
    print('Squre value:',x)
    break

while True:
    reply = input('Enter Input:')
    if reply == 'stop': break
    print(int(reply) ** 2)
    print('Exit')

S = '123'
T = 'xxx'
S.isdigit( ), T.isdigit( )

while True:
    reply = input('Enter text:')
    if reply == 'stop':
        break
    elif not reply.isdigit( ):
        print('Bad!' * 2)
else:
    print(int(reply) ** 2)
    print('Bye')

while True:
    reply = input('Enter text:')
    if reply == 'stop': break
    try:
        num = int(reply)
    except:
        print('Bad!' * 2)
    else:
        print(int(reply) ** 2)
        print('Bye')

while True:
    reply = input('Enter text:')
    if reply == 'stop':
        break
    elif not reply.isdigit( ):
        print('Bad!' * 8)
    else:
        num = int(reply)
        if num < 20:
            print('low')
        else:
            print(num ** 2)
print('Bye')

"""simple calculator using if statements"""

x= input("Enter Value 1st: ")
y= input("Enter Value 2nd: ")

print("Chose an operation: ")
print("1--> +")
print("2--> -")
print("3--> *")
print("4--> /")
sgn= input()

if sgn=='1':
        result=int(x)+int(y)
        print("Result:", result)
       

elif sgn=='2':
        result=int(x)-int(y)
        print("Result:", result)
            

elif sgn=='3':
        result=int(x)*int(y)
        print("Result:", result)
        

elif sgn=='4':
        result=int(x)/int(y)
        print("Result:", result)